name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PATH: Srmrlt/Action-test/.github/workflows

jobs:
  echo_rep_n:
    name: Test github.repository names2
    uses: $PATH/test.yml@main
